name: Deploy to AWS

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy Chalice application
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          TZ: ${{ vars.TZ }}
          SQS_SEND_EMAIL: ${{ vars.SQS_SEND_EMAIL }}
        run: |
          pip install chalice
          chalice deploy --no-autogen-policy
